# Application and Environment Configuration
spring:
  application:
    name: user-ms

# Database Configuration
  datasource:
    url: jdbc:postgresql://postgres:5432/user_db
    username: DemoTask
    password: DemoTask_987
    driver-class-name: org.postgresql.Driver

# JPA and Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      database-platform: org.hibernate.dialect.PostgreSQLDialect

# Liquibase Configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

# Server Configuration
server:
  port: 9080

# Security Configuration
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b

springdoc:
  swagger-ui:
    path: /swagger-ui.html