# Application and Environment Configuration
spring:
  application:
    name: user-ms

# Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: DemoTask
    password: DemoTask_987
    driver-class-name: org.postgresql.Driver

# JPA and Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      database-platform: org.hibernate.dialect.PostgreSQLDialect

# Liquibase Configuration
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml

# Server Configuration
server:
  port: 9080

# Security Configuration
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b

# Actuator Configuration
management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  info:
    env:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html